### ISSUE TITLE
Turn speed is not displayed

### ISSUE THREAD

**Issue by diegojcastro** [seurimas/starmourn-ship-builder#1]
The superstructure correctly parses turn speed into the superstructure object, but it does not seem like the html has any field that displays that value. It might be a worthwhile addition with the rest of the ship specs at the bottom left of the screen, between Thrust/Mass and Price. Alternatively, the Model dropdown from the top right could also include turn speed there for easy comparison.

**Comment by seurimas** [comment]
I will take care of this on Sunday, most likely.
