### ISSUE TITLE
New weapons and updates to old

### ISSUE THREAD

**Issue by bduza** [seurimas/starmourn-ship-builder#2]
Ships weapons have been overhauled.

https://docs.google.com/spreadsheets/d/11zOZ6MX5Z5bIg6DGIu5B0PcecILE9X9g7-QKI25YLm0/edit?usp=sharing

I've listed weapons and costs there, along with changes to fire rate, reload speed etc - if you do get around to updating this at some point, maybe that will help. Or when I have some spare time I'll have a crack at it myself, but what you've done here is very new to me so it'll take me a while to understand what to do/change.

**Comment by seurimas** [comment]
Thanks for sharing these. I've been hoping someone would do the hard part for me. I should be able to get these in tomorrow.
