### ISSUE TITLE
new ship modules and weapons etc

### ISSUE THREAD

**Issue by bduza** [seurimas/starmourn-ship-builder#5]
New stuff has been added. I couldn't figure out the react stuff to do this properly with a pull request, but at least this might help with the workload?

new modules:
https://pastebin.mozilla.org/uwqp06b8

changed module:
https://pastebin.mozilla.org/b0mfTV4T

new weapons:
https://pastebin.mozilla.org/fzUpyhRh

Hopefully I didn't miss any, make mistakes etc.

**Comment by seurimas** [comment]
It does help! I can basically slot those right and get fitting working, at the least.

**Comment by seurimas** [comment]
I've slotted this data in. Thanks for issue and the pastebins!
